import * as pdfjsLib from './vendor/pdfjs/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc = chrome.runtime.getURL('vendor/pdfjs/pdf.worker.min.mjs');

const fields = [['name','个人名字','input'],['politicalStatus','政治身份','input'],['school','院校','input'],['major','专业','input'],['education','学历','input'],['birthPlace','生源地','input'],['residence','现居住地','input'],['phone','手机号','input'],['email','邮箱','input'],['projects','项目经历','textarea full'],['awards','荣誉奖项 / 获奖','textarea full'],['campus','校内经历','textarea full'],['certificates','证书','textarea full'],['skills','技能特长','textarea full']];
const basicKeys = new Set(['name','politicalStatus','school','major','education','birthPlace','residence','phone','email']);
function render(profile) { const make = ([key,label,type]) => `<div class="field ${type.includes('full')?'full':''}"><label for="${key}">${label}</label>${type.startsWith('textarea') ? `<textarea id="${key}" placeholder="可填写多条内容，每条一行"></textarea>` : `<input id="${key}" type="text" placeholder="填写${label}">`}</div>`; document.querySelector('#basic').innerHTML = fields.filter(f => basicKeys.has(f[0])).map(make).join(''); document.querySelector('#experience').innerHTML = fields.filter(f => !basicKeys.has(f[0])).map(make).join(''); fields.forEach(([key]) => { document.getElementById(key).value = profile[key] || ''; }); }
async function load() { render(await getProfile()); }
async function save() { const profile = await getProfile(); fields.forEach(([key]) => { profile[key] = document.getElementById(key).value.trim(); }); await saveProfile(profile); const button = document.querySelector('#save'); button.textContent = '已保存 ✓'; setTimeout(() => button.textContent = '保存资料', 1600); }
function parseText(text) { const profile = {}; const patterns = {name: /(?:姓名|名字)\s*[:：]?\s*([^\n\s]{2,10})/,school: /(?:毕业院校|学校|院校)\s*[:：]?\s*([^\n]+)/,major: /专业\s*[:：]?\s*([^\n]+)/,phone: /(?:手机|联系电话|电话)\s*[:：]?\s*(1[3-9]\d{9})/,email: /(?:邮箱|电子邮箱)\s*[:：]?\s*([\w.-]+@[\w.-]+\.[A-Za-z]{2,})/,politicalStatus: /(?:政治面貌|政治身份)\s*[:：]?\s*([^\n]+)/,birthPlace: /(?:生源地|籍贯)\s*[:：]?\s*([^\n]+)/,residence: /(?:现居住地|居住地)\s*[:：]?\s*([^\n]+)/}; Object.entries(patterns).forEach(([key, regex]) => { const hit = text.match(regex); if (hit) profile[key] = hit[1].trim(); }); profile.resumeText = text; return profile; }
async function unzipDocx(buffer) { const bytes = new Uint8Array(buffer), view = new DataView(buffer), decoder = new TextDecoder(); let pos = 0, xml = ''; while (pos + 30 < bytes.length) { if (view.getUint32(pos, true) !== 0x04034b50) break; const method = view.getUint16(pos + 8, true), compressed = view.getUint32(pos + 18, true), nameLen = view.getUint16(pos + 26, true), extraLen = view.getUint16(pos + 28, true); const name = decoder.decode(bytes.slice(pos + 30, pos + 30 + nameLen)), start = pos + 30 + nameLen + extraLen, data = bytes.slice(start, start + compressed); if (name === 'word/document.xml') { let out = data; if (method === 8) { const ds = new DecompressionStream('deflate-raw'); out = new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer()); } xml = decoder.decode(out); break; } pos = start + compressed; } return xml.replace(/<w:tab\/>/g, '\t').replace(/<w:br\/>/g, '\n').replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<'); }
async function extractPdfWithPdfJs(file) { const pdf = await pdfjsLib.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise; let text = ''; for (let index = 1; index <= pdf.numPages; index++) { const content = await (await pdf.getPage(index)).getTextContent(); text += content.items.map(item => item.str).join(' ') + '\n'; } return { pdf, text }; }
async function ocrPdf(pdf, hint) { if (!globalThis.Tesseract) throw new Error('OCR 引擎没有加载完成'); const pages = Math.min(pdf.numPages, 3); const worker = await Tesseract.createWorker('chi_sim', 1, {workerPath: chrome.runtime.getURL('vendor/tesseract/worker.min.js'),corePath: chrome.runtime.getURL('vendor/tesseract-core/tesseract-core.wasm.js'),langPath: chrome.runtime.getURL('vendor/tessdata/'),workerBlobURL: false,logger: message => { if (message.status === 'recognizing text') hint.textContent = `正在离线识别扫描简历… ${Math.round((message.progress || 0) * 100)}%`; }}); let text = ''; try { for (let index = 1; index <= pages; index++) { hint.textContent = `正在离线识别第 ${index}/${pages} 页…`; const page = await pdf.getPage(index), viewport = page.getViewport({ scale: 2 }); const canvas = document.createElement('canvas'), context = canvas.getContext('2d'); canvas.width = viewport.width; canvas.height = viewport.height; await page.render({ canvasContext: context, viewport }).promise; text += (await worker.recognize(canvas)).data.text + '\n'; } } finally { await worker.terminate(); } return text; }
async function handleFile(file) { const hint = document.querySelector('#parseHint'), lower = file.name.toLowerCase(); hint.classList.remove('hidden'); hint.textContent = `正在读取「${file.name}」…`; let text = '', note = ''; try { if (lower.endsWith('.json')) { const json = JSON.parse(await file.text()); text = json.resumeText || Object.values(json).join('\n'); } else if (lower.endsWith('.txt')) text = await file.text(); else if (lower.endsWith('.docx')) { text = await unzipDocx(await file.arrayBuffer()); note = 'DOCX 文档文本'; } else if (lower.endsWith('.pdf')) { const result = await extractPdfWithPdfJs(file); text = result.text; note = 'PDF 文本层'; if (!text.trim()) { note = '扫描版 PDF，已使用离线 OCR'; text = await ocrPdf(result.pdf, hint); } } else text = new TextDecoder().decode(await file.arrayBuffer()); } catch (error) { hint.textContent = `无法读取「${file.name}」：${error.message || '文件格式不受支持'}`; return; } const parsed = parseText(text), profile = await getProfile(); Object.assign(profile, parsed, { resumeName: file.name }); await saveProfile(profile); render(profile); const count = Object.keys(parsed).filter(key => key !== 'resumeText' && parsed[key]).length; hint.textContent = `已读取「${file.name}」${note ? `（${note}）` : ''}，识别到 ${count} 个基础字段。已回填到下方表单，请核对后点击“保存资料”。`; }
document.querySelector('#save').onclick = save; document.querySelector('#resumeFile').onchange = event => event.target.files[0] && handleFile(event.target.files[0]); load();
